---
title: "p8105_hw5_jc4166"
author: "Jerri Chen"
date: "11/08/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(rvest)

```

## Problem 1
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

Write a function to replace the missing values per the following guidelines:  
*For numeric variables, you should fill in missing values with the mean of non-missing values  
*For character variables, you should fill in missing values with "virginica"  

```{r}
fill_missing_data = function(x) {
  if(is.numeric(x)){x = replace_na(x, mean(x, na.rm = TRUE))} 
  else if (is.character(x)){x = replace_na(x, "virginica")}
}
```

iris_with_missing =  map(iris_with_missing, fill_missing_data) %>% 
  as_tibble()

```{r}
missing_data = function(x) {
  output = vector(length = length(x))
  
  for (i in 1:length(x)) {
    if (is.numeric(x[i])) {
      mean_i = mean(x[!is.na(x)])
          if (!is.na(x[i])) {output[i] = x[i]} 
        else {output[i] = mean_i}
    }
    else if (is.character(x[i])) {
        if (!is.na(x[i])) {output[i] = x[i]} 
      else {output[i] = "virginica"}
    }
  }
  output
}

iris_with_missing =  map(iris_with_missing, missing_data) %>% 
  as_tibble()
```



## Problem 2
